create table if not exists managed_users (
  name text primary key,
  budget_limit double precision not null default 100,
  warning_threshold double precision not null default 80,
  status text not null default 'active',
  created_at text not null,
  updated_at text not null
);

create table if not exists api_keys (
  api_key_identity text primary key,
  user_name text not null,
  sensitive_id text,
  redacted_key text,
  platform_created_at text,
  status text not null default 'active',
  first_seen_at text not null,
  last_seen_at text not null,
  deleted_at text,
  final_cost double precision default 0,
  final_tokens bigint default 0,
  final_requests bigint default 0
);

create table if not exists usage_records (
  id bigint generated by default as identity primary key,
  recorded_at text not null,
  month integer not null,
  year integer not null,
  user_name text not null,
  cost double precision not null default 0,
  tokens bigint not null default 0,
  requests bigint not null default 0,
  models_info text,
  api_keys_info text,
  active_key_identities text,
  status text not null default 'observed'
);

create table if not exists events (
  event_key text primary key,
  created_at text not null,
  month integer not null,
  year integer not null,
  period_key text not null,
  user_name text not null,
  api_key_identity text,
  event_type text not null,
  reason text,
  cost double precision default 0,
  tokens bigint default 0,
  requests bigint default 0,
  payload text
);

create index if not exists idx_usage_user_recorded_at
on usage_records(user_name, recorded_at);

create index if not exists idx_usage_user_period_recorded_at
on usage_records(user_name, year, month, recorded_at);

create index if not exists idx_api_keys_user_status
on api_keys(user_name, status);

create index if not exists idx_api_keys_user_status_last_seen
on api_keys(user_name, status, last_seen_at);

create index if not exists idx_events_period_type
on events(period_key, event_type);

create index if not exists idx_events_user_type_period_created_at
on events(user_name, event_type, year, month, created_at);
